# Site settings
title: Zombu
author: Clark Winkelmann
description: Jouez au terrible jeu du Zombu !
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://zombu.rip" # the base hostname & protocol for your site

# Links settings
links:
    repo:
        game: https://github.com/clarkwinkelmann/zombu
        website: https://github.com/clarkwinkelmann/zombu.rip
    download:
        windows: https://github.com/clarkwinkelmann/zombu/releases/download/v1.1/Zombu_Setup_Windows.exe
        linux:   https://github.com/clarkwinkelmann/zombu/releases/download/v1.1/Zombu_Linux_64bit.tar.gz
    guide:
        fr: https://github.com/clarkwinkelmann/zombu/releases/download/v1.1/Mode_demploi.pdf
        en: https://github.com/clarkwinkelmann/zombu/releases/download/v1.1/User_Guide.pdf
    refs:
        clarkwinkelmann: https://clarkwinkelmann.com
        cpp: https://www.divtec.ch/
        bugnplay: http://www.bugnplay.ch
    license:
        game: https://github.com/clarkwinkelmann/zombu/blob/master/LICENSE.txt
        website: https://github.com/clarkwinkelmann/zombu.rip/blob/master/LICENSE
    bugtracker: https://github.com/clarkwinkelmann/zombu/issues

# Build settings
markdown: kramdown
exclude:
  - nbproject
  - README.md
  - LICENSE
